global:
  redis:
    addr: "127.0.0.1:6379"
    password: ""
  vectordb:
    pgurl: "postgres://shenlan:password@127.0.0.1:5432/shenlan"
  datasources:
    - name: Xstream
      repo: https://github.com/svc-design/Xstream
      path: docs
    - name: documents
      repo: https://github.com/svc-design/documents
      path: /
    - name: XControl
      repo: https://github.com/svc-design/XControl
      path: docs
sync:
  repo:
    proxy: socks5://127.0.0.1:1080  # 仅在同步仓库时使用代理

models:
  embedder:
    models: "bge-m3"
    endpoint: "http://127.0.0.1:9000/v1/embeddings"
  generator:
    models:
      - 'deepseek-r1:8b'
    endpoint: "http://127.0.0.1:11434/v1/chat/completions"

embedding:
  max_batch: 64
  dimension: 1024          #维度
  max_chars: 8000
  rate_limit_tpm: 120000

chunking:
  embed_toc: true
  max_tokens: 800
  overlap_tokens: 80
  prefer_heading_split: true
  include_exts: [".md", ".mdx"]
  ignore_dirs: [".git", "node_modules", "dist", "build"]

api:
  askai:
    timeout: 100
    retries: 3
